/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ResumeStudioRouteImport } from './routes/resume-studio'
import { Route as CareerSetupRouteImport } from './routes/career-setup'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashSkillRadarRouteImport } from './routes/_dash.skill-radar'
import { Route as DashSettingsRouteImport } from './routes/_dash.settings'
import { Route as DashResumeIntelligenceRouteImport } from './routes/_dash.resume-intelligence'
import { Route as DashReportsRouteImport } from './routes/_dash.reports'
import { Route as DashPortfolioBuilderRouteImport } from './routes/_dash.portfolio-builder'
import { Route as DashJobMatchRouteImport } from './routes/_dash.job-match'
import { Route as DashInterviewRouteImport } from './routes/_dash.interview'
import { Route as DashGrowthRouteImport } from './routes/_dash.growth'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeStudioRoute = ResumeStudioRouteImport.update({
  id: '/resume-studio',
  path: '/resume-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerSetupRoute = CareerSetupRouteImport.update({
  id: '/career-setup',
  path: '/career-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashSkillRadarRoute = DashSkillRadarRouteImport.update({
  id: '/skill-radar',
  path: '/skill-radar',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashResumeIntelligenceRoute = DashResumeIntelligenceRouteImport.update({
  id: '/resume-intelligence',
  path: '/resume-intelligence',
  getParentRoute: () => DashRoute,
} as any)
const DashReportsRoute = DashReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashRoute,
} as any)
const DashPortfolioBuilderRoute = DashPortfolioBuilderRouteImport.update({
  id: '/portfolio-builder',
  path: '/portfolio-builder',
  getParentRoute: () => DashRoute,
} as any)
const DashJobMatchRoute = DashJobMatchRouteImport.update({
  id: '/job-match',
  path: '/job-match',
  getParentRoute: () => DashRoute,
} as any)
const DashInterviewRoute = DashInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => DashRoute,
} as any)
const DashGrowthRoute = DashGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career-setup': typeof CareerSetupRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/workspace': typeof WorkspaceRoute
  '/dashboard': typeof DashDashboardRoute
  '/growth': typeof DashGrowthRoute
  '/interview': typeof DashInterviewRoute
  '/job-match': typeof DashJobMatchRoute
  '/portfolio-builder': typeof DashPortfolioBuilderRoute
  '/reports': typeof DashReportsRoute
  '/resume-intelligence': typeof DashResumeIntelligenceRoute
  '/settings': typeof DashSettingsRoute
  '/skill-radar': typeof DashSkillRadarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career-setup': typeof CareerSetupRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/workspace': typeof WorkspaceRoute
  '/dashboard': typeof DashDashboardRoute
  '/growth': typeof DashGrowthRoute
  '/interview': typeof DashInterviewRoute
  '/job-match': typeof DashJobMatchRoute
  '/portfolio-builder': typeof DashPortfolioBuilderRoute
  '/reports': typeof DashReportsRoute
  '/resume-intelligence': typeof DashResumeIntelligenceRoute
  '/settings': typeof DashSettingsRoute
  '/skill-radar': typeof DashSkillRadarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/career-setup': typeof CareerSetupRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/workspace': typeof WorkspaceRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/growth': typeof DashGrowthRoute
  '/_dash/interview': typeof DashInterviewRoute
  '/_dash/job-match': typeof DashJobMatchRoute
  '/_dash/portfolio-builder': typeof DashPortfolioBuilderRoute
  '/_dash/reports': typeof DashReportsRoute
  '/_dash/resume-intelligence': typeof DashResumeIntelligenceRoute
  '/_dash/settings': typeof DashSettingsRoute
  '/_dash/skill-radar': typeof DashSkillRadarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career-setup'
    | '/resume-studio'
    | '/workspace'
    | '/dashboard'
    | '/growth'
    | '/interview'
    | '/job-match'
    | '/portfolio-builder'
    | '/reports'
    | '/resume-intelligence'
    | '/settings'
    | '/skill-radar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career-setup'
    | '/resume-studio'
    | '/workspace'
    | '/dashboard'
    | '/growth'
    | '/interview'
    | '/job-match'
    | '/portfolio-builder'
    | '/reports'
    | '/resume-intelligence'
    | '/settings'
    | '/skill-radar'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/career-setup'
    | '/resume-studio'
    | '/workspace'
    | '/_dash/dashboard'
    | '/_dash/growth'
    | '/_dash/interview'
    | '/_dash/job-match'
    | '/_dash/portfolio-builder'
    | '/_dash/reports'
    | '/_dash/resume-intelligence'
    | '/_dash/settings'
    | '/_dash/skill-radar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  CareerSetupRoute: typeof CareerSetupRoute
  ResumeStudioRoute: typeof ResumeStudioRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-studio': {
      id: '/resume-studio'
      path: '/resume-studio'
      fullPath: '/resume-studio'
      preLoaderRoute: typeof ResumeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-setup': {
      id: '/career-setup'
      path: '/career-setup'
      fullPath: '/career-setup'
      preLoaderRoute: typeof CareerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/skill-radar': {
      id: '/_dash/skill-radar'
      path: '/skill-radar'
      fullPath: '/skill-radar'
      preLoaderRoute: typeof DashSkillRadarRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings': {
      id: '/_dash/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/resume-intelligence': {
      id: '/_dash/resume-intelligence'
      path: '/resume-intelligence'
      fullPath: '/resume-intelligence'
      preLoaderRoute: typeof DashResumeIntelligenceRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/reports': {
      id: '/_dash/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashReportsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/portfolio-builder': {
      id: '/_dash/portfolio-builder'
      path: '/portfolio-builder'
      fullPath: '/portfolio-builder'
      preLoaderRoute: typeof DashPortfolioBuilderRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/job-match': {
      id: '/_dash/job-match'
      path: '/job-match'
      fullPath: '/job-match'
      preLoaderRoute: typeof DashJobMatchRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/interview': {
      id: '/_dash/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof DashInterviewRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/growth': {
      id: '/_dash/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof DashGrowthRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashDashboardRoute: typeof DashDashboardRoute
  DashGrowthRoute: typeof DashGrowthRoute
  DashInterviewRoute: typeof DashInterviewRoute
  DashJobMatchRoute: typeof DashJobMatchRoute
  DashPortfolioBuilderRoute: typeof DashPortfolioBuilderRoute
  DashReportsRoute: typeof DashReportsRoute
  DashResumeIntelligenceRoute: typeof DashResumeIntelligenceRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashSkillRadarRoute: typeof DashSkillRadarRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashDashboardRoute: DashDashboardRoute,
  DashGrowthRoute: DashGrowthRoute,
  DashInterviewRoute: DashInterviewRoute,
  DashJobMatchRoute: DashJobMatchRoute,
  DashPortfolioBuilderRoute: DashPortfolioBuilderRoute,
  DashReportsRoute: DashReportsRoute,
  DashResumeIntelligenceRoute: DashResumeIntelligenceRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashSkillRadarRoute: DashSkillRadarRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  CareerSetupRoute: CareerSetupRoute,
  ResumeStudioRoute: ResumeStudioRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
